# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy #Name of the Workflow

on: #Name of the GitHub event that triggers the workflow
  push: #On Push Event We need to take action
    branches: #Now we need to specify the branch name
      - master

jobs: #Workflow run is made up of one or more jobs
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Build binary
        run: |
          cd extractor && zip deployment.zip main
#      - name: default deploy
#        uses: appleboy/lambda-action@master
#        with:
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws_region: ${{ secrets.AWS_REGION }}
#          function_name: gorush
#          zip_file: extractor/deployment.zip
#          memory_size: 128
#          timeout: 10
#          handler: foobar
#          role: arn:aws:iam::xxxxxxxxxxx:role/test1234
#          runtime: nodejs12.x


