# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy #Name of the Workflow

on: #Name of the GitHub event that triggers the workflow
  push: #On Push Event We need to take action
    branches: #Now we need to specify the branch name
      - master

jobs: #Workflow run is made up of one or more jobs
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip extractor dir
        run: zip -qq -r deployment.zip extractor
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: bd-jobs-scrapper-dev
          zip_file: deployment.zip
          memory_size: 128
          timeout: 10
          handler: scraper/lambda_function
          role: arn:aws:iam::940443069190:role/lambda_s3_ses
          layers: arn:aws:lambda:ap-southeast-1:940443069190:layer:puppeteer-chrome:2
          runtime: python3.8	

